### PR TITLE
Pull Request for MembersOnly Project

### PR DESCRIPTION
**Pull request by abouhid**
The aim of this project is practicing what we have learned about Authentication by creating a blog in which:
* You can create username, email and password;
* Create posts;
* Only signed in users can see the author of each post, when you are not logged in the posts are anonymous.

### CODE REVIEW

**Review by mikenath223 — CHANGES_REQUESTED** [review]
### Hi Team 👋

**Great work so far. 👍**

- [x] However, why does the `logout` button still show after signing out? Please fix it and we'll be good to go.

Kindly fix these issues and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

HAPPY CODING👨‍💻

**Comment by abouhid** [comment]
We decided to add some more features to our project, as adding profile pics for the users. Hope you enjoy :)

**Review by uche-inyama — CHANGES_REQUESTED** [review]
## Changes Required

### Hi team :wave: 

- I was not able to sign in to the application, not that I got an error, but rather, the form does not submit  However, there is no feedback regarding input validations, after several unsuccessful attempts to sign. up. 
- Please, display error messages due to input validations. This would help a user know right actions to take.

Kindly reach out if you have any clarifications on slack @Inyama, Uchechukwu Henry.

#### ``` Have a great day ``` :slightly_smiling_face: 

``` Uchechukwu Henry Inyama ```

**Review by mosesogwo — APPROVED** [review]
**Well done :clap: You can now :airplane:**

_**Cheers:stars:**_

### Status: Approved :heavy_check_mark:

**Pull request merged**
